language: node_js
node_js:
  - stable
before_script:
  - export TZ=America/Sao_Paulo
  - echo '$TZ' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - npm install
script:
  - npm run check
